name: install-deps
description: 'installs the app-specific dependencies'

inputs:
  app:
    required: true
    description: 'the app we install the deps of'

runs:
  using: 'composite'
  steps:
    - name: node application
      uses: err0r500/test-nx/.github/actions/languages/node@main
      if: contains(fromJson('["svc1", "svc2", "svc3"]'), inputs.app)
      with:
        app: ${{ inputs.app }}
