name: install-deps
description: 'todo'

inputs:
  app:
    required: true

runs:
  using: 'composite'
  steps:
    - run: echo ${{ inputs }}
      shell: bash

    - name: node application
      uses: err0r500/test-nx/.github/actions/node@main
      if: contains(fromJson('["svc1", "svc2", "svc3"]'), inputs.app)
      with:
        app: ${{ inputs.app }}
