name: nx
description: 'this action installs nx & and shared js dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install nx
      run: npm install -g nx
      shell: bash

    - name: install nx & shared deps
      run: npm install
      shell: bash
