name: node
description: 'this action install node app specific packages & run tests'

inputs:
  app:
    required: true
    description: 'the nx node app to test'

runs:
  using: 'composite'
  steps:
    - name: install app-specific deps
      run: cd ./apps/${{ inputs.app }} && npm install
      shell: bash

    # todo : remove tests from here
    - name: test !
      run: nx test ${{ inputs.app }}
      shell: bash
