name: dispatch

on: push

jobs:
  get-affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install nx
        run: npm install -g nx
      - name: install
        run: npm install
      - name: get affected projects
        id: get-affected-projects
        run: |
          echo "::set-output name=affected::$(nx print-affected --base HEAD^1 | jq -c '.projects')"
    outputs:
      affected: ${{ steps.get-affected-projects.outputs.affected }}




  test:
    runs-on: ubuntu-latest
    needs:
      - get-affected
    if: fromJson(needs.get-affected.outputs.affected)[0] != null
    strategy:
      matrix:
        project: ${{ fromJson(needs.get-affected.outputs.affected) }}
    steps:
      - id: trunk-flow
        run: |
          echo "::set-output name=is-trunk::${{ github.ref == 'refs/heads/main' }}"
      - uses: actions/checkout@v2
      - uses: err0r500/test-nx/.github/actions/nx@main
      - uses: err0r500/test-nx/.github/actions/install-deps@feat/pr-flow
        with:
          app: ${{ matrix.project }}




  docker-build:
    runs-on: ubuntu-latest
    needs:
      - get-affected
    if: fromJson(needs.get-affected.outputs.affected)[0] != null
      # && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        project: ${{ fromJson(needs.get-affected.outputs.affected) }}
    steps:
      - uses: actions/checkout@v2
      - uses: err0r500/test-nx/.github/actions/docker@feat/pr-flow
        with:
          app: ${{ matrix.project }}
          gitRef: ${{ github.sha }}



  deploy:
    runs-on: ubuntu-latest
    if: fromJson(needs.get-affected.outputs.affected)[0] != null
      # && ${{ github.event.inputs.trunk-flow }}
    needs:
      - get-affected
      - docker-build
      - test
    strategy:
      matrix:
        project: ${{ fromJson(needs.get-affected.outputs.affected) }}
    steps:
      - run: echo "deploy !"
      - if: job.status == 'sucess'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: ${{ matrix.project }}
          client-payload: '{"project": "${{ matrix.project }}", "sucess": true }'
      - if: job.status != 'sucess'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: ${{ matrix.project }}
          client-payload: '{"project": "${{ matrix.project }}", "sucess": false }'
